name: Pull Data DPD TPS

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *" # at GMT+7, it will run at 8:00 AM

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

permissions:
  actions: write
  contents: write

jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 300 # 5 hours
    steps:
      - uses: actions/checkout@v4
        # with:
        #   submodules: recursive

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install
      - name: Run
        run: bun start dpd get-tps-detail --no-dump
