name: Pull Data DPD TPS

on:
  schedule:
    - cron: "0 10 * * *" # at GMT+7, it will be run at 17:00
  # push:
  #   branches:
  #     - main
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 300 # 5 hours
    steps:
      - uses: actions/checkout@v4
        # with:
        #   submodules: recursive

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Run Batch 1
        run: bun start dpd get-tps-detail --no-dump -l 100000 -c 200

      - name: Run Batch 2
        run: bun start dpd get-tps-detail --no-dump -l 100000 -c 200

      - name: Run Batch 3
        run: bun start dpd get-tps-detail --no-dump -l 100000 -c 200

      - name: Run Batch 4
        run: bun start dpd get-tps-detail --no-dump -l 100000 -c 200

      - name: Run Batch 5
        run: bun start dpd get-tps-detail --no-dump -l 100000 -c 200

      - name: Run Batch 6
        run: bun start dpd get-tps-detail --no-dump -l 100000 -c 200

      - name: Run Batch 7
        run: bun start dpd get-tps-detail --no-dump -l 100000 -c 200

      - name: Run Batch 8
        run: bun start dpd get-tps-detail --no-dump -l 100000 -c 200

      - name: Run Batch 9
        run: bun start dpd get-tps-detail --no-dump -l 100000 -c 200
