name: Pull Data DPD

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 0 * * *" # at GMT+8, it will run at 8 AM

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

permissions:
  actions: write
  contents: write

jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 300 # 5 hours
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install
      - name: Run 1
        run: bun start dpd get-tps-detail -l 100000 --no-dump
