name: Release Database to Files

on:
  push
  # schedule:
  #   - cron: "0 0 * * *" # at GMT+8, it will run at 8 AM

jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 30 # 1 hour
    steps:
      - uses: actions/checkout@v4
      - run: whoami
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd Dump
            ./export.sh
