name: Pull Data Presiden dan Wakil Presiden

on: [push]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

permissions:
  actions: write
  contents: write

jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install
      - name: Run
        run: bun start dpd get-tps-detail -c 5 -l 20

      - name: Update Submodule
        run: |
          git submodule init
          git submodule update --remote

      - name: Make Changes and Push
        run: |
          # Navigate to the submodule directory
          cd dump

          # Make your changes (e.g., modify files)

          # Add and commit changes
          git add .
          git commit -m "Update submodule"

          # Push changes to the submodule's repository
          git push origin HEAD:main
