name: Release Database to Files

on:
  schedule:
    - cron: "0 */2 * * *" # run every 2 hours

jobs:
  run:
    runs-on: self-hosted
    timeout-minutes: 60 # 1 hour
    steps:
      - uses: actions/checkout@v4
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 60m # 1 hour
          script: |
            cd Dump
            ./export.sh
